### ISSUE TITLE
🎯 What can I work on ? (Odoo/OFF Connect)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/odoo-openfoodfacts#6]
### Import and create leads quickly (and possibly on the go)
- [ ] openfoodfacts/odoo-openfoodfacts#5 
- [ ] openfoodfacts/odoo-openfoodfacts#4 
- [ ] Share to Odoo Android intent
- [ ] https://github.com/openfoodfacts/odoo-openfoodfacts/issues/2

### Update leads quickly (and possibly on the go)
- [ ] openfoodfacts/odoo-openfoodfacts#5 
- [ ] openfoodfacts/odoo-openfoodfacts#4 

### Get information about a lead quickly (and possibly on the go)
- [ ] openfoodfacts/odoo-openfoodfacts#5 
- [ ] https://github.com/openfoodfacts/odoo-openfoodfacts/issues/3

### Quality of life improvements
- [ ] Autocomplete City/Street/… when adding a contact
- [ ] Company autocomplete for free
- [ ] Retroprocessing of all companies, adding logos, emails, websites
- [ ] Retroprocessing of all contacts whose name is an email
- [ ] Adding all food categories as industries ?
```
